### ISSUE TITLE
[question] RetroPie implementation ? Could not initialize x11 not found.

### ISSUE THREAD

**Issue by shad00m** [danmons/mame_raspberrypi_cross_compile#1]
Specs:
Rpi 4 2gb
Bullseye 32bit
RetroPie-Setup from source
SDL2 2.0.20 (seems that they reverted back to 2.0.10)
currently FKMS

Hey,
first off thanks of for this project it made it really easy to cross compile mame and save a lot of time. After pushing the 7z to my pi I got an error trying to start mame:

Could not initialize x11 not found.

It works fine when I'm in the GUI (startx) but it won't run from the terminal. Is it an SDL2 issue?

Glad for any tip you have :)

**Comment by shad00m** [comment]
The issue is related to: https://github.com/mamedev/mame/pull/9888
fixed by adding "videodriver kmsdrm" to mame.ini

**Comment by danmons** [comment]
Sorry for the delayed response.  Yes, you need to tell MAME blatantly how you want the video out to happen.  It'll attempt X11+SDL by default otherwise.
