### ISSUE TITLE
download_libs.sh not working because of wrong debian-archive-keyring name

### ISSUE THREAD

**Issue by loivire** [danmons/mame_raspberrypi_cross_compile#4]
In order to fix this script to dowload and extract deb files correctly i had to change this:

wget -c "${DEBMIRROR}/pool/main/d/debian-archive-keyring/debian-archive-keyring_2021.1.1_all.deb"
to:
 wget -c "${DEBMIRROR}/pool/main/d/debian-archive-keyring/debian-archive-keyring_2021.1.1+deb11u1_all.deb"

and:
dpkg -x "debian-archive-keyring_2021.1.1_all.deb" ./
to:
dpkg -x "debian-archive-keyring_2021.1.1+deb11u1_all.deb" ./

**Comment by danmons** [comment]
I've pushed a fix to always search for the latest signing keys by date and install them, rather than a hard-coded version/date string.
