### ISSUE TITLE
bookworm cross-compilation support

### ISSUE THREAD

**Issue by dzarras** [danmons/mame_raspberrypi_cross_compile#5]
Hi.

Even though there already exists a file defining the dependencies for bookworm, no crosstool-ng config exists for bookworm aarch64. Are there any plans to add support for targeting bookworm aarch64?

Thanks.

**Comment by danmons** [comment]
Debian 12 Bookworm support has been added to the latest version.  Please check the README for updates (there have been numerous changes).
