### ISSUE TITLE
expat-2.5.0 (digest verification failed)

### ISSUE THREAD

**Issue by mrgw454** [danmons/mame_raspberrypi_cross_compile#7]
Hello there.

Trying this out on a Debian 12 (x86_64) system for the first time and getting this error:

```
[EXTRA]    Retrieving 'expat-2.5.0'
[EXTRA]    Verifying SHA512 checksum for 'expat-2.5.0.tar.xz'
[ERROR]    Bad sha512 digest for expat-2.5.0.tar.xz: 84fc1dc892e50572b12da0b920e9ce192d5bed2de316c7528dbfbc5a7b2c61a8327cf7cddff0be647de9be4dcddf9ab26c4bd22f12913c5d226bd0d0cafd94c1, expect 2da73b991b7c0c54440485c787e5edeb3567230204e31b3cac1c3a6713ec6f9f1554d3afffc0f8336168dfd5df02db4a69bcf21b4d959723d14162d13ab87516
[ERROR]    Digest verification failed; removing the download
[ERROR]    expat: download failed
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@488]
[ERROR]  >>        called from: CT_DoFetch[scripts/functions@2130]
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@2090]
[ERROR]  >>        called from: CT_Fetch[scripts/functions@2201]
[ERROR]  >>        called from: do_expat_get[scripts/build/companion_libs/210-expat.sh@12]
[ERROR]  >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@649]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 0:17.18)
[00:17] / gmake: *** [/home/ron/source/mame_raspberrypi_cross_compile/build/ctng/1.26.0/bin/ct-ng:261: build] Error 1


```
Are there checksum values that need to be updated?

Thanks for any help you can provide!

**Comment by danmons** [comment]
I've built this a number of times over in the last few days without any errors.  One thing I notice is that attempting to run the `-o prepare` phase to build crosstool-ng has some bad error detection from ct-ng itself, and if downloads of upstream packages fail, it doesn't detect or retry that very well. 

Try deleting the `build/ctng/debian_12_bookworm_*` directories, and re-running the `-o prepare` phase to see if a second attempt works.  The good downloads are cached into the `build/src` directory, and won't need to be re-downloaded on a second attempt. 

Alternatively you can manually download the source bundle yourself from here:

```
https://github.com/libexpat/libexpat/releases/download/R_2_5_0/expat-2.5.0.tar.xz
```

Put that in `build/src`, and ct-ng should find and verify it without needing to download it.

**Comment by mrgw454** [comment]
Downloading the expat package manually manually resolved the issue.  Talk about a time saver -- takes about 10 minutes to build the development environment and about 12 minutes to compile MAME.  

Works great on my RPi400 and RPi5.  Will be testing on my RPi4 and RPi3 B+ soon.

Thanks so much for your help and for sharing this project!
